> Name: 張宸愷
> ID: 0710018



In [4]:
import pandas as pd
import sklearn as sk
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

mush = pd.read_csv("data/agaricus-lepiota.data", sep=",", header=None)
mush = mush.drop(columns=11) # drop features with '?'
mush = mush.sample(frac=1).reset_index(drop=True) # shuffle data

encoder = OrdinalEncoder(dtype=np.int8)
encoder.fit(mush)
mush = encoder.transform(mush)
print(mush)


[[1 3 2 ... 7 4 0]
 [1 2 3 ... 7 4 4]
 [0 0 0 ... 7 2 1]
 ...
 [0 5 3 ... 3 3 4]
 [0 5 3 ... 3 5 0]
 [1 5 0 ... 3 4 0]]


In [ ]:
from sklearn.naive_bayes import CategoricalNB
